### ISSUE TITLE
get indexEnd error错误 以及 建议再加入avatars.githubusercontent.com一项

### ISSUE THREAD

**Issue by MilesPoupart** [ovenx/github-hosts#1]
在ubuntu上运行 大多数情况运行到一半会出错，类似一下情况

start get host：
================
140.82.114.4 github.com
199.232.96.133 avatars7.githubusercontent.com
199.232.96.133 raw.githubusercontent.com
get indexEnd error avatars2.githubusercontent.com

start get host：
================
get indexEnd error gist.githubusercontent.com

另外，希望加入avatars.githubusercontent.com一项，更全面

**Comment by MilesPoupart** [comment]
可以加一下对比多个IP的时延选优的功能 :-P

**Comment by ovenx** [comment]
已添加 avatars.githubusercontent.com，获取 ip 错误想问下你那边网络是否可以正常访问 https://www.ipaddress.com/ip-lookup

**Comment by MilesPoupart** [comment]
可以访问的 我怀疑是请求太频繁 然后在获取ip的函数后面加了个time.Sleep(time.Duration(2)*time.Second) 就没再出现过这个错误了 但程序的实际运行表现也不像请求间隔两秒 也是很快能出结果 不是很搞得懂（没用Go语言编程过 找到这个项目现配的Go语言环境
